name: CI

on:
  push:
    branches:
        - master
  workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          env:
            XXX: ${{ secrets.XXX }}
          run: |
            echo "${GITHUB_REF_NAME}=${XXX}"
