name: CI

on:
  push:
    branches:
        - master
  workflow_dispatch:

env:
    XXX: ${{ secrets.XXX }}

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: |
            echo "${GITHUB_REF_NAME}=${XXX}"
