name: CI

on:
  push:
    branches:
        - master
  workflow_dispatch:

env:
    BRANCH: "${GITHUB_REF_NAME}"

jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: $BRANCH
      steps:
        - name: Deploy
          run: |
            echo "$BRANCH=${{ secrets.XXX }}"
